task: 'PPO-HC'
group: 'PPO'
device: 'cuda'
verbose: 2
env:
  config_path: null
  train_env_id : 'HCWithPos-v0'
  eval_env_id: 'HCWithPos-v0'  # 'HCWithPosTest-v0'
  save_dir: '../save_model'
  cost_info_str: ''
  use_cost: False
  reward_gamma: 0.99
  cost_gamma: null  # no cost
  dont_normalize_obs: False
  dont_normalize_reward: False
  dont_normalize_cost: True  # no cost
  record_info_names: ["xpos"]

running:
  n_iters: 30
  n_eval_episodes: 10
  save_every: 5

PPO:
  policy_name: 'MlpPolicy'
  learning_rate: 0.0003
  n_steps: 2048
  n_epochs: 10
  reward_gamma: 0.99
  reward_gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  reward_vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: False
  sde_sample_freq: -1
  target_kl: 0.01
  shared_layers: null
  policy_layers: [64, 64]
  reward_vf_layers: [64, 64]
  cost_vf_layers: False
  batch_size: 64
  eval_every: 2048
  use_curiosity_driven_exploration: False
  warmup_timesteps: False
  reset_policy: False
  forward_timesteps: 200000